Repository opensearch-project/dashboards-reporting, pull requests merged in 2023-01, with the labels that each got.

#18 Update Developer guide
  DEVELOPER_GUIDE.md
Labels: backport 2.x

#24 Add release notes for 2.5.0.0
  release-notes/opensearch-dashboards-reporting.release-notes-2.5.0.0.md
Labels: backport 2.5, backport main

#28 Updating plugin-helpers in package.json
  package.json
Labels: backport 2.x

#34 Update scrollX and scrollY values for html2canvas
  public/components/visual_report/generate_report.ts
Labels: backport 2.x, backport 2.5
