Repository opensearch-project/dashboards-reporting, pull requests merged in 2023-10, with the labels that each got.

#148 Fix date format in csv files
  server/routes/utils/__tests__/savedSearchReportHelper.test.ts
  server/routes/utils/dataReportHelpers.ts
Labels: backport 2.3

#211 2.11 Bug fix for checking Date Field presence
  server/routes/utils/dataReportHelpers.ts
Labels: backport 2.x, backport main, backport 2.10

#212 Support reporting in discover
  public/components/context_menu/context_menu.js
Labels: backport 2.x, backport main

#217 Release Notes 2.11
  release-notes/opensearch-dashboards-reporting.release-notes-2.11.0.0.md
Labels: backport 2.x, backport main

#221 Upgrade traverse to address CVE-2023-45133, resolve debug for CVE-2017-16137
  package.json
  yarn.lock
Labels: backport 2.x, backport 2.11

#229 Use core navigation instead of hard coding URLs
  public/components/context_menu/context_menu_helpers.js
  public/components/utils/application_service.ts
  public/plugin.ts
Labels: backport 2.x, backport 2.11
