Repository opensearch-project/dashboards-reporting, pull requests merged in 2023-04, with the labels that each got.

#86 Add tesseract and foreign object rendering
  NOTICE.txt
  common/tesseract/.gitignore
  package.json
  public/components/context_menu/context_menu_ui.js
  public/components/visual_report/assets/report_styles.ts
  public/components/visual_report/generate_report.ts
  scripts/postinstall.js
  server/plugin.ts
  server/routes/index.ts
  server/routes/tesseract.ts
  yarn.lock
Labels: backport 2.x, v2.7.0, backport 2.7

#89 Update jsdom version to remove request dependency
  package.json
  yarn.lock
Labels: backport 2.x, dependencies, v2.7.0, backport 2.7

#95 Add release notes for 2.7.0
  release-notes/opensearch-dashboards-reporting.release-notes-2.7.0.0.md
Labels: backport 2.x, backport 2.7

#102 Add fix for CVE-2023-2251
  package.json
  yarn.lock
Labels: backport 2.x, backport 1.3
