Repository opensearch-project/dashboards-reporting, pull requests merged in 2023-09, with the labels that each got.

#172 Update searchbar snapshots from upstream changes
  public/components/main/__tests__/__snapshots__/main.test.tsx.snap
  public/components/main/__tests__/__snapshots__/report_definitions_table.test.tsx.snap
  public/components/main/__tests__/__snapshots__/reports_table.test.tsx.snap
  public/components/main/report_definition_details/__tests__/__snapshots__/report_definition_details.test.tsx.snap
  public/components/main/report_details/__tests__/__snapshots__/report_details.test.tsx.snap
  public/components/report_definitions/report_settings/__tests__/__snapshots__/report_settings.test.tsx.snap
Labels: backport 2.x

#174 Bump @cypress/request to 3.0.0
  package.json
  yarn.lock
Labels: backport 2.x

#176 Add 2.10 Release notes
  release-notes/opensearch-dashboards-reporting.release-notes-2.10.0.0.md
Labels: backport 2.x

#184 support reporting for new discover
  public/components/context_menu/context_menu.js
  server/utils/__tests__/validationHelper.test.ts
  server/utils/validationHelper.ts
Labels: backport 2.x, backport 2.10

#190 Fix reporting discover
  public/components/context_menu/context_menu.js
  public/components/context_menu/context_menu_helpers.js
Labels: backport 2.x, backport main
