Repository opensearch-project/dashboards-reporting, pull requests merged in 2023-07, with the labels that each got.

#135 Upgrade tough-cookie and semver
  package.json
  yarn.lock
Labels: backport 2.x, dependencies, backport 2.9

#143 Add 2.9 release notes
  release-notes/opensearch-dashboards-reporting.release-notes-2.9.0.0.md
Labels: backport 2.9

#142 Update breadcrumb title of isDashboardNavMenu
  public/components/context_menu/context_menu.js
Labels: backport 2.x, backport main, v2.9.0

#154 bump word-wrap for cve fix
  package.json
  yarn.lock
Labels: backport 2.x
