Repository opensearch-project/dashboards-reporting, pull requests merged in 2024-02, with the labels that each got.

#286 Added release notes for 2.12
  release-notes/opensearch-dashboards-reporting.release-notes-2.12.0.0.md
Labels: backport 2.x, backport 2.12

#295 Reporting menu item
  .cypress/integration/04-download.spec.ts
  public/components/context_menu/context_menu.js
Labels: backport 2.12

#284 allow negative signs in duration
  server/utils/__tests__/validationHelper.test.ts
  server/utils/validationHelper.ts
Labels: backport 2.x

#303 [CI/CD] Add single version flag during bootstrap to fix version conflicts
  .github/workflows/cypress-e2e-reporting-test.yml
  .github/workflows/ftr-e2e-reporting-test.yml
  .github/workflows/lint.yml
Labels: backport 2.x

#299 Fix condition to determine if the date field's value is an array
  .cypress/integration/04-download.spec.ts
  .github/workflows/cypress-e2e-reporting-test.yml
  .github/workflows/dashboards-reports-test-and-build-workflow.yml
  DEVELOPER_GUIDE.md
  server/routes/utils/dataReportHelpers.ts
  yarn.lock
Labels: backport 2.x

#309 Fix undefined date error while generating CSV report
  server/routes/utils/dataReportHelpers.ts
Labels: backport 2.x

#313 Add workflow to verify binary installation is successful
  .github/workflows/verify-binary-installation.yml
Labels: backport 2.x
