Repository opensearch-project/dashboards-reporting, pull requests merged in 2024-09, with the labels that each got.

#416 [Bugfix] Update UI and handle new navigation
  public/components/app.tsx
  public/components/main/__tests__/__snapshots__/main.test.tsx.snap
  public/components/main/__tests__/__snapshots__/report_definitions_table.test.tsx.snap
  public/components/main/__tests__/__snapshots__/reports_table.test.tsx.snap
  public/components/main/__tests__/main.test.tsx
  public/components/main/loading_modal/loading_modal.tsx
  public/components/main/main.tsx
  public/components/main/report_definition_details/__tests__/__snapshots__/report_definition_details.test.tsx.snap
  public/components/main/report_definition_details/__tests__/report_definition_details.test.tsx
  public/components/main/report_definition_details/report_definition_details.tsx
  public/components/main/report_definitions_table.tsx
  public/components/main/report_details/__tests__/__snapshots__/report_details.test.tsx.snap
  public/components/main/report_details/report_details.tsx
  public/components/main/reports_table.tsx
  public/components/report_definitions/create/create_report_definition.tsx
  public/components/report_definitions/report_settings/__tests__/__snapshots__/report_settings.test.tsx.snap
  public/components/report_definitions/report_settings/report_settings.tsx
Labels: bug, backport 2.x, backport 2.17

#420 Add v2.17 release notes
  release-notes/opensearch-dashboards-reporting.release-notes-2.17.0.0.md
Labels: backport 2.x, backport 2.17

#423 Upgrade micromatch to 4.0.8
  package.json
  yarn.lock
Labels: backport 2.x, backport 2.17

#395 [Feature] Add the ability to configure record limit/count from the UI
  .cypress/integration/02-edit.spec.ts
  public/components/main/report_definition_details/report_definition_details.tsx
  public/components/main/report_details/report_details.tsx
  public/components/report_definitions/report_settings/report_settings.tsx
  release-notes/opensearch-dashboards-reporting.release-notes-2.17.0.0.md
Labels: enhancement, backport 2.x, v2.17.0, backport 2.17

#428 [Manual Backport] Allow arbitrary report record counts
  .cypress/integration/02-edit.spec.ts
  public/components/main/report_definition_details/report_definition_details.tsx
  public/components/main/report_details/report_details.tsx
  public/components/report_definitions/report_settings/report_settings.tsx
  release-notes/opensearch-dashboards-reporting.release-notes-2.17.0.0.md
Labels: enhancement

#427 [Manual Backport] Allow arbitrary report record counts
  .cypress/integration/02-edit.spec.ts
  public/components/main/report_definition_details/report_definition_details.tsx
  public/components/main/report_details/report_details.tsx
  public/components/report_definitions/report_settings/report_settings.tsx
  release-notes/opensearch-dashboards-reporting.release-notes-2.17.0.0.md
Labels: enhancement

#429 Update large record report warning
  public/components/report_definitions/report_settings/report_settings.tsx
Labels: enhancement, backport 2.x, backport 2.17

#430 [Manual backport] Update report with many records warning
  public/components/report_definitions/report_settings/report_settings.tsx
Labels: enhancement

#431 [Manual backport] Update report with many records warning
  public/components/report_definitions/report_settings/report_settings.tsx
Labels: enhancement

#432 Bump path-to-regexp to 1.9.0
  package.json
  release-notes/opensearch-dashboards-reporting.release-notes-2.17.0.0.md
  yarn.lock
Labels: backport 2.x, backport main

#444 [CVE-2024-45801] Bump `dompurify` from 2.4.7 to 2.5.6
  yarn.lock
Labels: backport 2.x, backport 2.17

#450 Add release note for 2.17.1
  release-notes/opensearch-dashboards-reporting.release-notes-2.17.1.0.md
Labels: backport 2.x, backport 2.17

#453 Fix the release note for 2.17.1
  release-notes/opensearch-dashboards-reporting.release-notes-2.17.1.0.md
Labels: backport 2.x, backport 2.17
