Repository opensearch-project/dashboards-reporting, pull requests merged in 2024-12, with the labels that each got.

#479 [CVE] Address CVE issues
  package.json
  public/components/report_definitions/report_settings/report_settings.tsx
  server/routes/utils/constants.ts
  yarn.lock
Labels: backport 1.x

#482 Add 1.3 release notes
  release-notes/opensearch-dashboards-reports.release-notes-1.3.20.0.md
Labels: backport 1.x, release, v1.3.20

#476 Sanitize markdown when previewing report header/footer
  public/components/main/__tests__/__snapshots__/main.test.tsx.snap
  public/components/main/__tests__/__snapshots__/reports_table.test.tsx.snap
  public/components/report_definitions/report_settings/report_settings.tsx
Labels: backport 2.x, backport 1.3
