Repository opensearch-project/dashboards-reporting, pull requests merged in 2024-07, with the labels that each got.

#369 [Navigation] Register all plugins to NavGroups
  public/plugin.ts
  public/plugin_nav.tsx
Labels: backport 2.x

#379 [Look&Feel] Adjust header and text sizes in reporting menu options
  public/components/context_menu/context_menu_ui.js
Labels: backport 2.x, v2.16.0

#382 [Backport 2.x] Update dependency jsdom to v18
  package.json
  yarn.lock
Labels: backport 2.16

#385 Update dependency ws to v7.5.10
  package.json
  yarn.lock
Labels: backport 2.x, backport 2.16

#386 [Backport 2.x] Update dependency ws to v7.5.10
  package.json
  yarn.lock
Labels: backport 2.16

#388 Add braces v3.0.3 to resolution
  package.json
  yarn.lock
Labels: backport 2.x, backport 2.16

#390 Add v2.16.0 release notes
  release-notes/opensearch-dashboards-reporting.release-notes-2.16.0.0.md
Labels: backport 2.x, backport 2.16

#389 [Backport 2.x] Add braces v3.0.3 to resolution
  package.json
  yarn.lock
Labels: backport 2.16
