Repository opensearch-project/dashboards-reporting, pull requests merged in 2025-03, with the labels that each got.

#536 Bump dashboards reporting to version 3.0.0.0-alpha1
  .github/workflows/cypress-e2e-reporting-test.yml
  .github/workflows/dashboards-reports-test-and-build-workflow.yml
  .github/workflows/ftr-e2e-reporting-test.yml
  .github/workflows/verify-binary-installation.yml
  opensearch_dashboards.json
  package.json
Labels: maintenance

#554 [Bug] Updated the optional parameters for timefrom and timeto
  server/model/index.ts
  server/routes/utils/converters/backendToUi.ts
Labels: bug

#555 bump jspdf to 3.0.1
  package.json
  yarn.lock
Labels: backport 2.19
