Repository opensearch-project/dashboards-reporting, pull requests merged in 2025-02, with the labels that each got.

#511 [CVE-2024-47875] Bump dompurify to 3.2.4
  package.json
  yarn.lock
Labels: backport 2.x, backport 2.19

#516 Change dompurify version to 3.0.11 to match OSD
  package.json
  yarn.lock
Labels: backport 2.x, backport 2.19

#529 Bump jspdf to 3.0 to fix CVE-2025-26791
  package.json
  yarn.lock
Labels: backport 2.x, backport 2.19, maintenance

#530 [Manual backport 2.x] Bump jspdf to 3.0 to fix CVE-2025-26791
  package.json
  yarn.lock
Labels: backport 2.19
