Repository opensearch-project/dashboards-reporting, pull requests merged in 2025-04, with the labels that each got.

#558 [CVE] fix CVE issue CVE-2025-27789
  package.json
  yarn.lock
Labels: security fix, maintenance

#559 Remove cypress and babel jest from project dependency list
  .github/workflows/cypress-e2e-reporting-test.yml
  package.json
  yarn.lock
Labels: maintenance

#570 [Bug] Reporting Popover UI
  .cypress/integration/04-download.spec.ts
  public/components/context_menu/context_menu.js
  public/components/context_menu/context_menu_helpers.js
  public/components/context_menu/context_menu_ui.js
Labels: bug, backport 3.0
